export { default as Home } from './Home'
export { default as Footer } from './Footer'
export { default as About } from './About'
export { default as Experiences } from './Experiences'
export { default as Projects } from './Projects'